# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

require 'rubygems'
require 'motion-testflight'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'SitecoreReader'
  app.device_family = [:ipad, :iphone]
  app.deployment_target = "5.0"
  app.icons = [ 'rubymotion-icon.jpg' ]

  # Use `rake config' to see complete project settings.


  # app.vendor_project(
  #     '../../deployment/SitecoreMobileSDK.framework', :static,
  #     :products => ['SitecoreMobileSDK'],
  #     :headers_dir => 'Headers')

  app.vendor_project(
      '../../lib-third-party/PublicAutomation', :xcode,
      :target => ['PublicAutomation'],
      :headers_dir => 'PublicAutomation')


  app.vendor_project(
      '../../lib-ruby-third-party/MotionBlocks', :xcode,
      :target => ['MotionBlocks'],
      :headers_dir => 'MotionBlocks')

  app.frameworks +=
      [ 'MapKit', 'CoreLocation', 'CoreMotion',
        'CoreMedia', 'CoreVideo', 'AVFoundation', 'AudioToolbox',
        'MessageUI', 'Twitter', 'AddressBookUI', 'AddressBook',
        'CFNetwork', 'UIKit', 'Foundation', 'CoreGraphics' ]


  libPath_ = '/usr/lib/'

  libs_ = [ 'libz.dylib', 'libsqlite3.dylib', 'libxml2.dylib', 'libc++.dylib', 'libstdc++.dylib', 'libiconv.dylib' ]
  wrappedLibs_ = libs_.map { |libName_| libPath_ + libName_  }

  puts wrappedLibs_

  app.libs += wrappedLibs_


  #app.codesign_certificate = 'iPhone Developer: Igor Khomich (S92MV9NQHF)'
  #app.provisioning_profile = '/Users/Igor/Library/MobileDevice/Provisioning Profiles/09D6A45D-3112-47A1-9D0A-D13155FC3C46.mobileprovision'
  #
  #
  ### @adk account
  app.codesign_certificate = 'iPhone Developer: Oleksandr Dodatko (V3H7RLLSD5)'
  app.provisioning_profile = '/Users/cert/Mobile_SDK.mobileprovision'

  app.testflight.api_token = 'a3620a9760dc97411328bc73864c9a82_Mzk2NDIxMjAxMi0wNC0xMyAwNDowNzozMS42MDQ2NTQ'
  #
  ## "RubyMotionResearch" team
  app.testflight.team_token = '9a4cf26c2ba6dab0ae956567f92fc0c0_ODA1NzEyMDEyLTA0LTEzIDA0OjEzOjM5LjA5OTQ0Nw'
  #
  app.testflight.distribution_lists = ['Mobile Team']
  app.testflight.notify = true



  app.files =
      Dir.glob( File.join( app.project_dir, '../../lib-ruby-third-party/MotionBlocks/*.rb' ) ) |
      Dir.glob( File.join( app.project_dir, '../../lib-ruby/SRModel/SRModel/*.rb'     ) ) |
      Dir.glob( File.join( app.project_dir, '../../lib-ruby/SRLoaders/SRLoaders/*.rb' ) ) |
      Dir.glob( File.join( app.project_dir, 'app/**/*.rb'                             ) ) |
      Dir.glob( File.join( app.project_dir, 'app/*.rb'                                ) ) |
      app.files;
end
