# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

require 'rubygems'
# require 'motion-testflight'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'SitecoreReader'
  app.device_family = [:ipad, :iphone]
  app.deployment_target = "5.0"
  app.icons = [ 'rubymotion-icon.jpg' ]

  # Use `rake config' to see complete project settings.


  # app.vendor_project(
  #     '../../deployment/SitecoreMobileSDK.framework', :static,
  #     :products => ['SitecoreMobileSDK'],
  #     :headers_dir => 'Headers')

  app.vendor_project(
      '../../lib-third-party/PublicAutomation', :xcode,
      :target => ['PublicAutomation'],
      :headers_dir => 'PublicAutomation')


  app.vendor_project(
      '../../lib-ruby-third-party/MotionBlocks', :xcode,
      :target => ['MotionBlocks'],
      :headers_dir => 'MotionBlocks')

  app.frameworks +=
      [ 'MapKit', 'CoreLocation', 'CoreMotion',
        'CoreMedia', 'CoreVideo', 'AVFoundation', 'AudioToolbox',
        'MessageUI', 'Twitter', 'AddressBookUI', 'AddressBook',
        'CFNetwork', 'UIKit', 'Foundation', 'CoreGraphics' ]


  libPath_ = '/usr/lib/'

  libs_ = [ 'libz.dylib', 'libsqlite3.dylib', 'libxml2.dylib', 'libc++.dylib', 'libstdc++.dylib', 'libiconv.dylib' ]
  wrappedLibs_ = libs_.map { |libName_| libPath_ + libName_  }

  puts wrappedLibs_

  app.libs += wrappedLibs_


  app.files =
      Dir.glob( File.join( app.project_dir, '../../lib-ruby-third-party/MotionBlocks/*.rb' ) ) |
      Dir.glob( File.join( app.project_dir, '../../lib-ruby/SRModel/SRModel/*.rb'     ) ) |
      Dir.glob( File.join( app.project_dir, '../../lib-ruby/SRLoaders/SRLoaders/*.rb' ) ) |
      Dir.glob( File.join( app.project_dir, 'app/**/*.rb'                             ) ) |
      Dir.glob( File.join( app.project_dir, 'app/*.rb'                                ) ) |
      app.files;
end
